use crate::model::MetadataEntry;
use crate::svg::parse_json_object;
use std::io::Read;

pub const MAX_PDF_READ_SIZE: u64 = 32 * 1024 * 1024; // 32 MB safety limit

/// Fast, allocation-free case-insensitive substring search
pub fn contains_ignore_ascii_case(haystack: &[u8], needle: &[u8]) -> bool {
    if needle.is_empty() || haystack.len() < needle.len() {
        return false;
    }
    haystack.windows(needle.len()).any(|window| {
        window
            .iter()
            .zip(needle.iter())
            .all(|(&a, &b)| a.eq_ignore_ascii_case(&b))
    })
}

/// Verifies whether the PDF file was generated by Matplotlib or smart_savefig
pub fn is_matplotlib_pdf(content: &[u8]) -> bool {
    if !content.starts_with(b"%PDF-") {
        return false;
    }
    contains_ignore_ascii_case(content, b"matplotlib")
        || contains_ignore_ascii_case(content, b"smart_savefig")
}

fn decode_pdf_string(bytes: &[u8]) -> String {
    // Check for UTF-16BE BOM
    if bytes.len() >= 2 && bytes[0] == 0xFE && bytes[1] == 0xFF {
        let u16s: Vec<u16> = bytes[2..]
            .chunks_exact(2)
            .map(|c| u16::from_be_bytes([c[0], c[1]]))
            .collect();
        String::from_utf16_lossy(&u16s)
    } else {
        String::from_utf8(bytes.to_vec())
            .unwrap_or_else(|_| bytes.iter().map(|&b| b as char).collect())
    }
}

fn decode_hex_string(hex_bytes: &[u8]) -> Vec<u8> {
    let clean: Vec<u8> = hex_bytes
        .iter()
        .copied()
        .filter(|b| !b.is_ascii_whitespace())
        .collect();
    let mut out = Vec::with_capacity(clean.len() / 2);
    let mut i = 0;
    while i < clean.len() {
        if i + 1 < clean.len() {
            if let Ok(b) =
                u8::from_str_radix(std::str::from_utf8(&clean[i..i + 2]).unwrap_or(""), 16)
            {
                out.push(b);
            }
            i += 2;
        } else {
            let s = format!("{}0", clean[i] as char);
            if let Ok(b) = u8::from_str_radix(&s, 16) {
                out.push(b);
            }
            i += 1;
        }
    }
    out
}

/// Finds the end of a balanced dictionary `<< ... >>` skipping nested strings
pub fn find_dict_end(slice: &[u8]) -> Option<usize> {
    if !slice.starts_with(b"<<") {
        return None;
    }
    let mut depth = 0;
    let mut i = 0;
    let n = slice.len();

    while i < n {
        if slice[i..].starts_with(b"<<") {
            depth += 1;
            i += 2;
        } else if slice[i..].starts_with(b">>") {
            depth -= 1;
            i += 2;
            if depth == 0 {
                return Some(i);
            }
        } else if slice[i] == b'(' {
            // Skip string literals with balanced/escaped parens
            i += 1;
            let mut str_depth = 1;
            while i < n && str_depth > 0 {
                if slice[i] == b'\\' && i + 1 < n {
                    i += 2;
                } else if slice[i] == b'(' {
                    str_depth += 1;
                    i += 1;
                } else if slice[i] == b')' {
                    str_depth -= 1;
                    i += 1;
                } else {
                    i += 1;
                }
            }
        } else if slice[i] == b'<' && (i + 1 < n && slice[i + 1] != b'<') {
            // Skip hex string literals <...>
            i += 1;
            while i < n && slice[i] != b'>' {
                i += 1;
            }
            if i < n {
                i += 1;
            }
        } else {
            i += 1;
        }
    }
    None
}

/// Locates the Info dictionary either through trailer resolution or signature matching
pub fn find_info_dict(content: &[u8]) -> Option<&[u8]> {
    // Strategy 1: Search backwards for trailer /Info reference
    if let Some(trailer_pos) = content.windows(7).rposition(|w| w == b"trailer") {
        let trailer_slice = &content[trailer_pos..];
        if let Some(d_start) = trailer_slice.windows(2).position(|w| w == b"<<") {
            if let Some(d_len) = find_dict_end(&trailer_slice[d_start..]) {
                let trailer_dict = &trailer_slice[d_start..d_start + d_len];
                if let Some(info_kw) = trailer_dict.windows(5).position(|w| w == b"/Info") {
                    let after_info = &trailer_dict[info_kw + 5..];
                    let trimmed = after_info
                        .iter()
                        .skip_while(|b| b.is_ascii_whitespace())
                        .copied()
                        .collect::<Vec<u8>>();
                    let num_end = trimmed
                        .iter()
                        .position(|b| !b.is_ascii_digit())
                        .unwrap_or(0);
                    if num_end > 0 {
                        if let Ok(obj_num_str) = std::str::from_utf8(&trimmed[..num_end]) {
                            let target = format!("{} 0 obj", obj_num_str);
                            if let Some(obj_pos) = content
                                .windows(target.len())
                                .position(|w| w == target.as_bytes())
                            {
                                let after_obj = &content[obj_pos + target.len()..];
                                if let Some(dict_start) =
                                    after_obj.windows(2).position(|w| w == b"<<")
                                {
                                    if let Some(dict_len) =
                                        find_dict_end(&after_obj[dict_start..])
                                    {
                                        return Some(
                                            &after_obj[dict_start..dict_start + dict_len],
                                        );
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    // Strategy 2: Direct scan for the dictionary containing Matplotlib metadata
    let mut cursor = 0;
    while let Some(rel_start) = content[cursor..].windows(2).position(|w| w == b"<<") {
        let abs_start = cursor + rel_start;
        if let Some(dict_len) = find_dict_end(&content[abs_start..]) {
            let candidate = &content[abs_start..abs_start + dict_len];
            if contains_ignore_ascii_case(candidate, b"smart_savefig")
                || (contains_ignore_ascii_case(candidate, b"/Producer")
                    && contains_ignore_ascii_case(candidate, b"matplotlib"))
            {
                return Some(candidate);
            }
            cursor = abs_start + dict_len;
        } else {
            cursor = abs_start + 2;
        }
    }

    None
}

/// Parses key-value pairs from a PDF dictionary
pub fn parse_pdf_dict(dict_bytes: &[u8]) -> Vec<(String, String)> {
    let mut entries = Vec::new();
    let mut i = 0;
    let n = dict_bytes.len();

    while i < n {
        if dict_bytes[i] == b'/' {
            i += 1;
            let key_start = i;
            while i < n
                && !dict_bytes[i].is_ascii_whitespace()
                && dict_bytes[i] != b'('
                && dict_bytes[i] != b'<'
                && dict_bytes[i] != b'/'
                && dict_bytes[i] != b'['
                && dict_bytes[i] != b'>'
            {
                i += 1;
            }
            let key = String::from_utf8_lossy(&dict_bytes[key_start..i]).to_string();

            while i < n && dict_bytes[i].is_ascii_whitespace() {
                i += 1;
            }

            if i < n && dict_bytes[i] == b'(' {
                i += 1;
                let mut depth = 1;
                let mut val_bytes = Vec::new();
                while i < n && depth > 0 {
                    if dict_bytes[i] == b'\\' && i + 1 < n {
                        i += 1;
                        match dict_bytes[i] {
                            b'n' => val_bytes.push(b'\n'),
                            b'r' => val_bytes.push(b'\r'),
                            b't' => val_bytes.push(b'\t'),
                            b'b' => val_bytes.push(0x08),
                            b'f' => val_bytes.push(0x0C),
                            b'(' => val_bytes.push(b'('),
                            b')' => val_bytes.push(b')'),
                            b'\\' => val_bytes.push(b'\\'),
                            b'0'..=b'7' => {
                                let mut oct = (dict_bytes[i] - b'0') as u8;
                                if i + 1 < n && (b'0'..=b'7').contains(&dict_bytes[i + 1]) {
                                    i += 1;
                                    oct = oct * 8 + (dict_bytes[i] - b'0');
                                    if i + 1 < n && (b'0'..=b'7').contains(&dict_bytes[i + 1]) {
                                        i += 1;
                                        oct = oct * 8 + (dict_bytes[i] - b'0');
                                    }
                                }
                                val_bytes.push(oct);
                            }
                            other => val_bytes.push(other),
                        }
                    } else if dict_bytes[i] == b'(' {
                        depth += 1;
                        val_bytes.push(b'(');
                    } else if dict_bytes[i] == b')' {
                        depth -= 1;
                        if depth > 0 {
                            val_bytes.push(b')');
                        }
                    } else {
                        val_bytes.push(dict_bytes[i]);
                    }
                    i += 1;
                }
                let val = decode_pdf_string(&val_bytes);
                entries.push((key, val));
            } else if i < n && dict_bytes[i] == b'<' && (i + 1 == n || dict_bytes[i + 1] != b'<') {
                i += 1;
                let hex_start = i;
                while i < n && dict_bytes[i] != b'>' {
                    i += 1;
                }
                let hex_slice = &dict_bytes[hex_start..i];
                if i < n && dict_bytes[i] == b'>' {
                    i += 1;
                }
                let val_bytes = decode_hex_string(hex_slice);
                let val = decode_pdf_string(&val_bytes);
                entries.push((key, val));
            } else {
                while i < n && dict_bytes[i] != b'/' && dict_bytes[i] != b'>' {
                    i += 1;
                }
            }
        } else {
            i += 1;
        }
    }
    entries
}

pub fn extract_pdf_metadata<R: Read>(reader: &mut R) -> std::io::Result<Vec<MetadataEntry>> {
    let mut content = Vec::new();
    reader.take(MAX_PDF_READ_SIZE).read_to_end(&mut content)?;

    // Reject non-PDFs and non-matplotlib documents immediately
    if !is_matplotlib_pdf(&content) {
        return Ok(Vec::new());
    }

    let dict_bytes = match find_info_dict(&content) {
        Some(d) => d,
        None => return Ok(Vec::new()),
    };

    let raw_entries = parse_pdf_dict(dict_bytes);
    let mut entries = Vec::new();

    for (key, val) in raw_entries {
        let trimmed_val = val.trim();
         // Automatically unpack embedded JSON payload (e.g. from /Keywords)
        if trimmed_val.starts_with('{') && trimmed_val.ends_with('}') {
            if let Some(json_entries) = parse_json_object(trimmed_val, 0) {
                for (jk, jv) in json_entries {
                    entries.push(MetadataEntry {
                        key: format!("{}/{}", key, jk),
                        value: jv,
                    });
                }
                continue;
            }
        }
        entries.push(MetadataEntry { key, value: val });
    }

    Ok(entries)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::resolve_key;
    use std::io::Cursor;

    #[test]
    fn test_matplotlib_pdf_detection_and_extraction() {
        let synthetic_pdf = br#"%PDF-1.4
1 0 obj
<< /Type /Catalog /Pages 2 0 R >>
endobj
10 0 obj
<<
  /Title (equilibrium_plot.pdf)
  /Author (solve_flux)
  /Subject (smart_savefig: equilibrium_plot.pdf)
  /Creator (matplotlib version 3.8.2)
  /Producer (Matplotlib pdf backend)
  /Keywords ({"directory": "/home/user/sim", "source_code": "import numpy as np\ndef solve(): pass\n", "git_commit": "abcdef1"})
>>
endobj
trailer
<< /Size 11 /Root 1 0 R /Info 10 0 R >>
startxref
500
%%EOF"#;

        let mut cursor = Cursor::new(synthetic_pdf.to_vec());
        let entries = extract_pdf_metadata(&mut cursor).unwrap();

        assert_eq!(
            resolve_key(&entries, "Title").unwrap().value,
            "equilibrium_plot.pdf"
        );
        assert_eq!(
            resolve_key(&entries, "source_code").unwrap().value,
            "import numpy as np\ndef solve(): pass\n"
        );
        assert_eq!(
            resolve_key(&entries, "SourceCode").unwrap().value,
            "import numpy as np\ndef solve(): pass\n"
        );
        assert_eq!(
            resolve_key(&entries, "git_commit").unwrap().value,
            "abcdef1"
        );
    }

    #[test]
    fn test_non_matplotlib_pdf_ignored() {
        // Standard non-matplotlib document (e.g., compiled with LaTeX / InDesign)
        let latex_pdf = br#"%PDF-1.5
1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj
5 0 obj
<<
  /Title (Quantum Electrodynamics)
  /Creator (LaTeX with hyperref)
  /Producer (pdfTeX-1.40.25)
>>
endobj
trailer << /Root 1 0 R /Info 5 0 R >>
%%EOF"#;

        let mut cursor = Cursor::new(latex_pdf.to_vec());
        let entries = extract_pdf_metadata(&mut cursor).unwrap();
        // Must return empty vector to avoid polluting search results
        assert!(entries.is_empty());
    }

    #[test]
    fn test_pdf_string_escapes() {
        let dict = br#"<< /Comment (Plot with \(nested\) parens and \n newline) >>"#;
        let entries = parse_pdf_dict(dict);
        assert_eq!(entries.len(), 1);
        assert_eq!(entries[0].0, "Comment");
        assert_eq!(entries[0].1, "Plot with (nested) parens and \n newline");
    }
}